[package]
name = "gw2lib"
version = "3.0.1"
edition = "2021"
workspace = "../"
description = "A simple to use Gw2 API wrapper library"
repository = "https://github.com/greaka/gw2lib"
categories = ["api-bindings"]
keywords = ["api", "guild-wars-2", "gw2", "wrapper", "async"]
readme = "../README.md"
license = "MIT/Apache-2.0"

[lib]
name = "gw2lib"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.24"
dashmap = "5.4.0"
serde = "1.0.160"
thiserror = "1.0.40"
async-trait = "0.1.68"
either = "1.8.1"
futures = "0.3.28"
serde_json = "1.0.96"
static_init = "1.0.3"
urlencoding = "2.1.2"

[dependencies.tracing]
version = "0.1.37"
optional = true

[dependencies.redis]
version = "0.23.0"
default-features = false
features = ["tokio-comp"]
optional = true

[dependencies.tokio]
version = "1.27.0"
default-features = false
features = ["sync", "rt", "time"]

[dependencies.hyper]
version = "0.14.26"
default-features = false
features = ["runtime", "http1", "client"]

[dependencies.hyper-rustls]
version = "0.24.0"
default-features = false
features = ["http1", "native-tokio", "logging", "tls12"]

[dependencies.gw2lib-model]
version = "2.0.5"
path = "../model"

[features]
blocking = []
redis = ["dep:redis"]
tracing = ["dep:tracing"]

[package.metadata.docs.rs]
features = ["redis"]
